name: Trigger auto deployment for cap-dev-weather-01

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/cap-dev-weather-01-AutoDeployTrigger-73509fbf-6a3e-48b2-ac74-be0fd74912f9.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: mytestcontainerreg001.azurecr.io
          username: ${{ secrets.CAPDEVWEATHER01_REGISTRY_USERNAME }}
          password: ${{ secrets.CAPDEVWEATHER01_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: mytestcontainerreg001.azurecr.io/cap-dev-weather-01:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CAPDEVWEATHER01_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n cap-dev-weather-01 -g azsu-rg-dev-weather-01 --server mytestcontainerreg001.azurecr.io --username  ${{ secrets.CAPDEVWEATHER01_REGISTRY_USERNAME }} --password ${{ secrets.CAPDEVWEATHER01_REGISTRY_PASSWORD }}
            az containerapp update -n cap-dev-weather-01 -g azsu-rg-dev-weather-01 --image mytestcontainerreg001.azurecr.io/cap-dev-weather-01:${{ github.sha }} --container-name weatherapp-01
